import { randomUUID } from 'node:crypto';

import type { LlmClient } from '@bb/core';
import { getContentItemById, getQaResultForVersion, upsertVisualAsset } from '@bb/db';
import type { Queryable } from '@bb/db';
import type { VisualAsset } from '@bb/shared-types';

import { decideAndBrief } from './decideAndBrief.js';
import type { DecideAndBriefOutput } from './decideAndBrief.js';
import { VisualBlockedMissingTruthLayerError, VisualContentNotFoundError } from './errors.js';
import { buildGenerationPrompt, buildNegativePrompt } from './promptBuilder.js';

export interface PrepareVisualBriefInput {
  contentId: string;
  pool: Queryable;
  llm: LlmClient;
  runId: string;
}

// The fields every VisualAsset shares regardless of how the pixels are eventually
// obtained (Gemini API vs. a manually generated file) — everything except the
// three fields that only make sense once bytes exist: status, qa, masterAsset,
// blockingReasons.
export type VisualAssetBase = Omit<
  VisualAsset,
  'status' | 'qa' | 'masterAsset' | 'blockingReasons'
>;

export const emptyMasterAsset = {
  status: 'NONE' as const,
  provider: null,
  model: null,
  generationId: null,
  assetPath: null,
  assetUrl: null,
  mimeType: null,
  width: null,
  height: null,
  createdAt: null,
};

export interface PendingGeneration {
  kind: 'pending';
  visualId: string;
  baseAsset: VisualAssetBase;
  decision: DecideAndBriefOutput;
  prompt: string;
  negativePrompt: string;
  aspectRatio: string;
}

export interface TerminalDecision {
  kind: 'terminal';
  asset: VisualAsset;
}

export type PrepareVisualBriefResult = PendingGeneration | TerminalDecision;

function buildBaseAsset(
  visualId: string,
  contentId: string,
  version: number,
  decision: DecideAndBriefOutput,
): VisualAssetBase {
  const now = new Date().toISOString();
  return {
    id: visualId,
    contentId,
    version,
    visualDecision: decision.visualDecision,
    visualType: decision.visualType,
    concept: decision.concept,
    rationale: decision.rationale,
    sourceMode: decision.sourceMode,
    isAiGenerated: decision.sourceMode === 'ai_generated' || decision.sourceMode === 'hybrid',
    isIllustrative: decision.isIllustrative,
    disclosureRequired: decision.disclosureRequired,
    generationBrief: decision.generationBrief,
    visualClaims: decision.visualClaims,
    fictionalOrIllustrativeElements: decision.fictionalOrIllustrativeElements,
    riskFlags: decision.riskFlags,
    platformVariants: {},
    createdAt: now,
    updatedAt: now,
  };
}

// The "decide + brief" half of the visual stage, shared by both the automated path
// (runVisualStage.ts, calls a configured image provider) and the manual path
// (ingestManualVisualAsset.ts, for an image generated by a human/Claude driving a
// browser session — see .agents/skills/bb-visual-agent). Persists a
// GENERATION_PENDING row so the manual path can pick this brief back up in a later,
// separate call once the image actually exists.
export async function prepareVisualBrief(
  input: PrepareVisualBriefInput,
): Promise<PrepareVisualBriefResult> {
  const item = await getContentItemById(input.pool, input.contentId);
  if (!item) throw new VisualContentNotFoundError(input.contentId);

  const qaResult = await getQaResultForVersion(input.pool, input.contentId, item.currentVersion);
  if (!item.coreClaim && !qaResult) {
    throw new VisualBlockedMissingTruthLayerError(input.contentId);
  }

  const visualId = randomUUID();
  const stepId = `visual:${visualId}`;

  const decision = await decideAndBrief({
    contentId: input.contentId,
    platform: item.platform,
    topic: item.topic,
    coreClaim: item.coreClaim,
    currentText: item.currentText,
    sourceUrls: item.sourceUrls,
    llm: input.llm,
    runId: input.runId,
    stepId,
  });

  const baseAsset = buildBaseAsset(visualId, input.contentId, item.currentVersion, decision);

  if (decision.visualDecision === 'NOT_APPROPRIATE') {
    const asset = await upsertVisualAsset(input.pool, {
      ...baseAsset,
      status: 'NOT_REQUIRED',
      qa: null,
      masterAsset: emptyMasterAsset,
      blockingReasons: [],
    });
    return { kind: 'terminal', asset };
  }

  if (decision.visualDecision === 'REAL_ASSET_REQUIRED') {
    const asset = await upsertVisualAsset(input.pool, {
      ...baseAsset,
      status: 'BRIEF_READY',
      qa: null,
      masterAsset: emptyMasterAsset,
      blockingReasons: [
        'REAL_ASSET_REQUIRED: this story depends on a real, sourced artifact. A human must supply ' +
          'it directly — it cannot be AI-generated.',
      ],
    });
    return { kind: 'terminal', asset };
  }

  // Persisted so a manual-ingestion call (which may happen minutes later, in a
  // separate process/session — a browser-driven generation isn't instant) can
  // recover this exact brief/claims without re-running the LLM decision step.
  await upsertVisualAsset(input.pool, {
    ...baseAsset,
    status: 'GENERATION_PENDING',
    qa: null,
    masterAsset: emptyMasterAsset,
    blockingReasons: [],
  });

  return {
    kind: 'pending',
    visualId,
    baseAsset,
    decision,
    prompt: buildGenerationPrompt(decision.generationBrief),
    negativePrompt: buildNegativePrompt(decision.generationBrief),
    aspectRatio: decision.generationBrief.aspectRatio,
  };
}
